[build]
  command = "npm run build"
  publish = "out"

# If you're using Next.js API routes or server-side features
[build.environment]
  NEXT_USE_SSR = "true"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
